name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        default: staging
    secrets:
      AWS_ROLE_ARN:
        required: true
      DOCKER_REPO:
        required: true
      SLACK_WEBHOOK:
        required: true

permissions: {}

jobs:
  call-workflow:
    uses: mbta/workflows/.github/workflows/deploy-ecs.yml@5c46d99bcf742a09983588d30a2b3ffed710decd # v4.0.1
    permissions:
      id-token: write
      contents: read
    with:
      app-name: mbta-metro
      environment: ${{ inputs.environment }}
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
      docker-repo: ${{ secrets.DOCKER_REPO }}
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
